name: iconsax_plus
description: "Iconsax are the official icons of the Vuesax framework, these icons can be used for personal and commercial use for free"
version: 0.0.1
homepage: https://iconsax.io/
repository: https://github.com/moha-b/Iconsax-Plus
issue_tracker: https://github.com/luisDanielRoviraContreras/flutter_iconsax/issues
documentation: https://github.com/moha-b/Iconsax-Plus?tab=readme-ov-file#flutter_iconsax
topics:
  - icons
  - iconsax
  - flutter
  - dart


environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IconsaxPlusBold
      fonts:
        - asset: fonts/IconsaxPlusBold.ttf
    - family: IconsaxPlusBroken
      fonts:
        - asset: fonts/IconsaxPlusBroken.ttf
    - family: IconsaxPlusLinear
      fonts:
        - asset: fonts/IconsaxPlusLinear.ttf
